spring:
  application:
    name: pethome

  datasource:
    password: marsel55
    username: postgres
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/postgres
    driver-class-name: org.postgresql.Driver

    hikari:
      schema: pethome
      maximum-pool-size: 2

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

#  mail:
#    password: dtftttdtbnktfvje
#    default-encoding: UTF-8
#    host: smtp.gmail.com
#    protocol: smtp
#    username: marsel.gabitov.74@gmail.com
#    port: 587
#    properties:
#      mail:
#        smtp:
#          auth: true
#          starttls:
#            enable: true

  mail:
    password: xPW6ad2sfeXjanB2UNq2
    default-encoding: UTF-8
    host: smtp.mail.ru
    protocol: smtp
    username: marsel.gabitov.74@mail.ru
    port: 465
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true



server:
  port: 8080
