GET http://localhost:8080/missing?type=LOST

###

GET http://localhost:8080/missing/owner/d4fb0b3c-cc99-4f76-9043-ae6a1d7ac756

###

POST http://localhost:8080/missing
Content-Type: application/json


{
  "posX": 10.3,
  "posY": 10.4,
  "description": "пропала собачка",
  "name": "boris",
  "district": {
    "name": "Московский район",
    "city": "Казань"
  },
  "owner": {
    "id": "d4fb0b3c-cc99-4f76-9043-ae6a1d7ac756"
  },
  "type": "LOST",
  "status": "ACTIVE"
}


###

DELETE http://localhost:8080/missing/821b00b1-f030-42aa-8c6a-6f679d65f28b

###

GET http://localhost:8080/missing/fact